package org.valkyrienskies.skyriders.content

import org.joml.Vector3d

data class BikePhysicsConfig(
    val mass: Double,
    val collisionBoxSize: Vector3d,
    val collisionBoxOffset: Vector3d,
    val frontWheelLocalPos: Vector3d,
    val rearWheelLocalPos: Vector3d,
    val wheelRadius: Double,
    val wheelWidth: Double,
    val suspensionRestLength: Double,
    val suspensionTravel: Double,
    val suspensionStrength: Double,
    val suspensionDamping: Double,
    val lateralGrip: Double,
    val longitudinalGrip: Double,
    val wheelTopSpeed: Double,
    val brakeStrength: Double,
    val frictionCoefficient: Double,
    val slipSharpness: Double,
    val tirePacejkaB: Double,
    val tirePacejkaC: Double,
    val tirePacejkaE: Double,
    val driftMinSpeed: Double,
    val driftRearGripScale: Double,
    val driftFrontGripScale: Double,
    val driftBrakeStrengthScale: Double,
    val driftDriveForceScale: Double,
    val driftYawAssist: Double,
    val driftBoostEnabled: Boolean,
    val driftBoostMaxLevel: Int,
    val driftBoostChargeTimes: List<Double>,
    val driftBoostForces: List<Double>,
    val driftBoostDurations: List<Double>,
    val maxSteerLowSpeedRad: Double,
    val maxSteerHighSpeedRad: Double,
    val steeringLowSpeedEnd: Double,
    val steeringHighSpeedStart: Double,
    val maxLeanAngleRad: Double,
    val minLeanSpeed: Double,
    val fullLeanSpeed: Double,
    val balanceStrength: Double,
    val balanceDamping: Double,
    val uprightAssistStartSpeed: Double,
    val uprightAssistEndSpeed: Double,
    val lowSpeedYawAssist: Double,
    val highSpeedYawAssist: Double,
    val maxStepHeight: Double,
    val stepAssistStrength: Double,
    val groundNormalSmoothingTime: Double,
    val maxPitchAngleRad: Double,
    val maxRollAngleRad: Double,
    val maxAngularVelocity: Double,
    val antiFlipStrength: Double,
    val airbornePitchControlStrength: Double,
    val airborneRollControlStrength: Double,
    val airborneBrakeDamping: Double,
    val maxWheelieAngleRad: Double,
    val maxStoppieAngleRad: Double,
    val groundedPitchControlStrength: Double,
    val pitchLimitStrength: Double,
    val pitchLimitDamping: Double,
    val parkingBalanceStrengthScale: Double,
    val parkingBalanceDampingScale: Double,
    val parkingBrakeStrength: Double,
    val parkingYawDamping: Double,
    val jumpChargeRate: Double,
    val jumpCompressionForce: Double,
    val jumpReleaseForce: Double,
    val jumpForwardBoostForce: Double,
    val jumpReleaseDuration: Double
) {
    companion object {
        val DEBUG_MOTORCYCLE = BikePhysicsConfig(
            mass = 250.0,
            collisionBoxSize = Vector3d(0.45, 0.55, 1.2),
            collisionBoxOffset = Vector3d(0.0, 0.25, -0.1),
            frontWheelLocalPos = Vector3d(0.0, -0.15, 0.8),
            rearWheelLocalPos = Vector3d(0.0, -0.15, -0.8),
            wheelRadius = 0.35,
            wheelWidth = 0.25,
            suspensionRestLength = 0.25,
            suspensionTravel = 0.45,
            suspensionStrength = 45000.0,
            suspensionDamping = 4500.0,
            lateralGrip = 1.0,
            longitudinalGrip = 1.0,
            wheelTopSpeed = 18.0,
            brakeStrength = 3.0,
            frictionCoefficient = 1.2,
            slipSharpness = 3.0,
            tirePacejkaB = 9.5,
            tirePacejkaC = 1.35,
            tirePacejkaE = 0.85,
            driftMinSpeed = 4.0,
            driftRearGripScale = 0.16,
            driftFrontGripScale = 0.38,
            driftBrakeStrengthScale = 0.0,
            driftDriveForceScale = 1.0,
            driftYawAssist = 1300.0,
            driftBoostEnabled = true,
            driftBoostMaxLevel = 3,
            driftBoostChargeTimes = listOf(0.85, 1.7, 2.8),
            driftBoostForces = listOf(4200.0, 6500.0, 9000.0),
            driftBoostDurations = listOf(0.35, 0.55, 0.8),
            maxSteerLowSpeedRad = Math.toRadians(32.0),
            maxSteerHighSpeedRad = Math.toRadians(22.0),
            steeringLowSpeedEnd = 3.0,
            steeringHighSpeedStart = 14.0,
            maxLeanAngleRad = Math.toRadians(38.0),
            minLeanSpeed = 3.0,
            fullLeanSpeed = 12.0,
            balanceStrength = 9000.0,
            balanceDamping = 1500.0,
            uprightAssistStartSpeed = 2.0,
            uprightAssistEndSpeed = 8.0,
            lowSpeedYawAssist = 1500.0,
            highSpeedYawAssist = 3600.0,
            maxStepHeight = 1.0,
            stepAssistStrength = 7000.0,
            groundNormalSmoothingTime = 0.08,
            maxPitchAngleRad = Math.toRadians(55.0),
            maxRollAngleRad = Math.toRadians(65.0),
            maxAngularVelocity = 8.0,
            antiFlipStrength = 4000.0,
            airbornePitchControlStrength = 1800.0,
            airborneRollControlStrength = 850.0,
            airborneBrakeDamping = 450.0,
            maxWheelieAngleRad = Math.toRadians(28.0),
            maxStoppieAngleRad = Math.toRadians(22.0),
            groundedPitchControlStrength = 6500.0,
            pitchLimitStrength = 9000.0,
            pitchLimitDamping = 1300.0,
            parkingBalanceStrengthScale = 1.15,
            parkingBalanceDampingScale = 1.4,
            parkingBrakeStrength = 4.5,
            parkingYawDamping = 900.0,
            jumpChargeRate = 1.45,
            jumpCompressionForce = 20000.0,
            jumpReleaseForce = 32000.0,
            jumpForwardBoostForce = 6500.0,
            jumpReleaseDuration = 0.06
        )
    }
}
