package org.valkyrienskies.skyriders.content

import org.joml.Vector3d

data class BikePhysicsConfig(
    val mass: Double,
    val collisionBoxSize: Vector3d,
    val collisionBoxOffset: Vector3d,
    val frontWheelLocalPos: Vector3d,
    val rearWheelLocalPos: Vector3d,
    val wheelRadius: Double,
    val wheelWidth: Double,
    val suspensionRestLength: Double,
    val suspensionTravel: Double,
    val suspensionStrength: Double,
    val suspensionDamping: Double,
    val lateralGrip: Double,
    val longitudinalGrip: Double,
    val wheelTopSpeed: Double,
    val brakeStrength: Double,
    val frictionCoefficient: Double,
    val slipSharpness: Double,
    val tirePacejkaB: Double,
    val tirePacejkaC: Double,
    val tirePacejkaE: Double,
    val driftMinSpeed: Double,
    val driftRearGripScale: Double,
    val driftFrontGripScale: Double,
    val driftBrakeStrengthScale: Double,
    val driftDriveForceScale: Double,
    val driftYawAssist: Double,
    val driftBoostEnabled: Boolean,
    val driftBoostMaxLevel: Int,
    val driftBoostChargeTimes: List<Double>,
    val driftBoostForces: List<Double>,
    val driftBoostDurations: List<Double>,
    val maxSteerLowSpeedRad: Double,
    val maxSteerHighSpeedRad: Double,
    val steeringLowSpeedEnd: Double,
    val steeringHighSpeedStart: Double,
    val maxLeanAngleRad: Double,
    val minLeanSpeed: Double,
    val fullLeanSpeed: Double,
    val balanceStrength: Double,
    val balanceDamping: Double,
    val uprightAssistStartSpeed: Double,
    val uprightAssistEndSpeed: Double,
    val lowSpeedYawAssist: Double,
    val highSpeedYawAssist: Double,
    val maxStepHeight: Double,
    val stepAssistStrength: Double,
    val groundNormalSmoothingTime: Double,
    val landingDampingEnabled: Boolean,
    val landingDampingDuration: Double,
    val landingVerticalDamping: Double,
    val landingAngularDamping: Double,
    val maxPitchAngleRad: Double,
    val maxRollAngleRad: Double,
    val maxAngularVelocity: Double,
    val antiFlipStrength: Double,
    val airbornePitchControlStrength: Double,
    val airborneRollControlStrength: Double,
    val airborneBrakeDamping: Double,
    val maxWheelieAngleRad: Double,
    val maxStoppieAngleRad: Double,
    val groundedPitchControlStrength: Double,
    val pitchLimitStrength: Double,
    val pitchLimitDamping: Double,
    val parkingBalanceStrengthScale: Double,
    val parkingBalanceDampingScale: Double,
    val parkingBrakeStrength: Double,
    val parkingYawDamping: Double,
    val jumpChargeRate: Double,
    val jumpCompressionForce: Double,
    val jumpReleaseForce: Double,
    val jumpForwardBoostForce: Double,
    val jumpReleaseDuration: Double
) {
    companion object {
        val MOTORCYCLE = BikePhysicsConfig(
            mass = 250.0,
            collisionBoxSize = Vector3d(0.45, 0.55, 1.2),
            collisionBoxOffset = Vector3d(0.0, 0.25, -0.1),
            frontWheelLocalPos = Vector3d(0.0, -0.15, 0.8),
            rearWheelLocalPos = Vector3d(0.0, -0.15, -0.8),
            wheelRadius = 0.35,
            wheelWidth = 0.25,
            suspensionRestLength = 0.25,
            suspensionTravel = 0.45,
            suspensionStrength = 45000.0,
            suspensionDamping = 4500.0,
            lateralGrip = 1.0,
            longitudinalGrip = 1.0,
            wheelTopSpeed = 18.0,
            brakeStrength = 3.0,
            frictionCoefficient = 1.2,
            slipSharpness = 3.0,
            tirePacejkaB = 9.5,
            tirePacejkaC = 1.35,
            tirePacejkaE = 0.85,
            driftMinSpeed = 4.0,
            driftRearGripScale = 0.16,
            driftFrontGripScale = 0.38,
            driftBrakeStrengthScale = 0.0,
            driftDriveForceScale = 1.0,
            driftYawAssist = 1900.0,
            driftBoostEnabled = true,
            driftBoostMaxLevel = 3,
            driftBoostChargeTimes = listOf(0.85, 1.7, 2.8),
            driftBoostForces = listOf(4200.0, 6500.0, 9000.0),
            driftBoostDurations = listOf(0.35, 0.55, 0.8),
            maxSteerLowSpeedRad = Math.toRadians(32.0),
            maxSteerHighSpeedRad = Math.toRadians(22.0),
            steeringLowSpeedEnd = 3.0,
            steeringHighSpeedStart = 14.0,
            maxLeanAngleRad = Math.toRadians(38.0),
            minLeanSpeed = 3.0,
            fullLeanSpeed = 12.0,
            balanceStrength = 9000.0,
            balanceDamping = 1500.0,
            uprightAssistStartSpeed = 2.0,
            uprightAssistEndSpeed = 8.0,
            lowSpeedYawAssist = 1500.0,
            highSpeedYawAssist = 3600.0,
            maxStepHeight = 1.0,
            stepAssistStrength = 7000.0,
            groundNormalSmoothingTime = 0.08,
            landingDampingEnabled = true,
            landingDampingDuration = 0.08,
            landingVerticalDamping = 24.0,
            landingAngularDamping = 450.0,
            maxPitchAngleRad = Math.toRadians(55.0),
            maxRollAngleRad = Math.toRadians(65.0),
            maxAngularVelocity = 8.0,
            antiFlipStrength = 4000.0,
            airbornePitchControlStrength = 1800.0,
            airborneRollControlStrength = 850.0,
            airborneBrakeDamping = 450.0,
            maxWheelieAngleRad = Math.toRadians(28.0),
            maxStoppieAngleRad = Math.toRadians(22.0),
            groundedPitchControlStrength = 6500.0,
            pitchLimitStrength = 9000.0,
            pitchLimitDamping = 1300.0,
            parkingBalanceStrengthScale = 1.15,
            parkingBalanceDampingScale = 1.4,
            parkingBrakeStrength = 4.5,
            parkingYawDamping = 900.0,
            jumpChargeRate = 1.45,
            jumpCompressionForce = 20000.0,
            jumpReleaseForce = 32000.0,
            jumpForwardBoostForce = 6500.0,
            jumpReleaseDuration = 0.06
        )

        val DIRT_BIKE = MOTORCYCLE.copy(
            mass = 210.0,
            collisionBoxSize = Vector3d(0.5, 0.62, 1.38),
            collisionBoxOffset = Vector3d(0.0, 0.27, 0.0),
            frontWheelLocalPos = Vector3d(0.0, -0.15, 0.69),
            rearWheelLocalPos = Vector3d(0.0, -0.15, -0.69),
            wheelRadius = 0.275,
            wheelWidth = 0.175,
            suspensionRestLength = 0.225,
            suspensionTravel = 0.25,
            suspensionStrength = 26000.0,
            suspensionDamping = 6500.0,
            wheelTopSpeed = 20.0,
            maxSteerLowSpeedRad = Math.toRadians(36.0),
            maxSteerHighSpeedRad = Math.toRadians(24.0),
            steeringHighSpeedStart = 15.0,
            maxLeanAngleRad = Math.toRadians(36.0),
            fullLeanSpeed = 13.0,
            balanceStrength = 6500.0,
            balanceDamping = 1900.0,
            highSpeedYawAssist = 2600.0,
            maxStepHeight = 1.0,
            stepAssistStrength = 2600.0,
            landingDampingDuration = 0.12,
            landingVerticalDamping = 32.0,
            landingAngularDamping = 650.0,
            maxWheelieAngleRad = Math.toRadians(34.0),
            maxStoppieAngleRad = Math.toRadians(24.0),
            driftYawAssist = 1500.0,
            jumpCompressionForce = 23000.0,
            jumpReleaseForce = 38000.0,
            jumpForwardBoostForce = 7600.0,
            driftBoostForces = listOf(4600.0, 7000.0, 9800.0)
        )

        val CRUISER = MOTORCYCLE.copy(
            mass = 360.0,
            collisionBoxSize = Vector3d(0.55, 0.6, 1.45),
            collisionBoxOffset = Vector3d(0.0, 0.25, -0.05),
            frontWheelLocalPos = Vector3d(0.0, -0.15, 0.95),
            rearWheelLocalPos = Vector3d(0.0, -0.15, -0.95),
            suspensionRestLength = 0.23,
            suspensionTravel = 0.38,
            suspensionStrength = 56000.0,
            suspensionDamping = 6200.0,
            wheelTopSpeed = 16.0,
            brakeStrength = 3.4,
            driftMinSpeed = 4.5,
            driftRearGripScale = 0.22,
            driftFrontGripScale = 0.45,
            driftYawAssist = 1250.0,
            driftBoostForces = listOf(3200.0, 5000.0, 7000.0),
            driftBoostDurations = listOf(0.3, 0.45, 0.65),
            maxSteerLowSpeedRad = Math.toRadians(28.0),
            maxSteerHighSpeedRad = Math.toRadians(15.0),
            steeringLowSpeedEnd = 2.5,
            steeringHighSpeedStart = 12.0,
            maxLeanAngleRad = Math.toRadians(30.0),
            minLeanSpeed = 3.5,
            fullLeanSpeed = 13.0,
            balanceStrength = 11000.0,
            balanceDamping = 2100.0,
            lowSpeedYawAssist = 1200.0,
            highSpeedYawAssist = 2100.0,
            maxStepHeight = 0.75,
            stepAssistStrength = 5200.0,
            landingDampingDuration = 0.1,
            landingVerticalDamping = 22.0,
            landingAngularDamping = 750.0,
            airbornePitchControlStrength = 1200.0,
            airborneRollControlStrength = 550.0,
            maxWheelieAngleRad = Math.toRadians(18.0),
            maxStoppieAngleRad = Math.toRadians(16.0),
            groundedPitchControlStrength = 4200.0,
            jumpCompressionForce = 15000.0,
            jumpReleaseForce = 22000.0,
            jumpForwardBoostForce = 4200.0
        )

        val HOVER_BIKE = MOTORCYCLE.copy(
            mass = 230.0,
            collisionBoxSize = Vector3d(0.5, 0.5, 1.25),
            collisionBoxOffset = Vector3d(0.0, 0.28, -0.05),
            frontWheelLocalPos = Vector3d(0.0, -0.12, 0.72),
            rearWheelLocalPos = Vector3d(0.0, -0.12, -0.72),
            wheelRadius = 0.3,
            suspensionRestLength = 0.85,
            suspensionTravel = 0.55,
            suspensionStrength = 26000.0,
            suspensionDamping = 4200.0,
            lateralGrip = 0.55,
            longitudinalGrip = 1.15,
            wheelTopSpeed = 22.0,
            brakeStrength = 2.4,
            driftBoostEnabled = false,
            maxSteerLowSpeedRad = Math.toRadians(24.0),
            maxSteerHighSpeedRad = Math.toRadians(18.0),
            maxLeanAngleRad = Math.toRadians(26.0),
            minLeanSpeed = 2.0,
            fullLeanSpeed = 14.0,
            balanceStrength = 7800.0,
            balanceDamping = 1500.0,
            lowSpeedYawAssist = 1200.0,
            highSpeedYawAssist = 2700.0,
            maxStepHeight = 0.0,
            stepAssistStrength = 0.0,
            landingDampingEnabled = false,
            maxPitchAngleRad = Math.toRadians(45.0),
            maxRollAngleRad = Math.toRadians(45.0),
            airbornePitchControlStrength = 1100.0,
            airborneRollControlStrength = 700.0,
            groundedPitchControlStrength = 2600.0,
            jumpChargeRate = 0.0,
            jumpCompressionForce = 0.0,
            jumpReleaseForce = 0.0,
            jumpForwardBoostForce = 0.0
        )
    }
}
