package org.valkyrienskies.skyriders.content

import org.joml.Vector3d

data class KartPhysicsConfig(
    val mass: Double,
    val collisionBoxSize: Vector3d,
    val collisionBoxOffset: Vector3d,
    val wheelLocalPositions: List<Vector3d>,
    val wheelRadius: Double,
    val wheelSampleWidth: Double = wheelRadius * 0.9,
    val wheelSweepTime: Double = 0.06,
    val suspensionRestLength: Double,
    val suspensionTravel: Double,
    val suspensionStrength: Double,
    val suspensionDamping: Double,
    val driveForce: Double,
    val brakeForce: Double,
    val parkingBrakeStrength: Double = 5.0,
    val lateralGrip: Double,
    val maxSteerRad: Double,
    val wheelTopSpeed: Double,
    val yawAssist: Double,
    val uprightStrength: Double,
    val uprightDamping: Double,
    val maxSteerHighSpeedRad: Double = maxSteerRad * 0.42,
    val steeringHighSpeedStart: Double = 4.0,
    val steeringFullSpeed: Double = 14.0,
    val steerSmoothingTime: Double = 0.11,
    val tireFrictionCoefficient: Double = 1.35,
    val frontLateralGrip: Double = lateralGrip,
    val rearLateralGrip: Double = lateralGrip,
    val lateralSlipShape: Double = 0.24,
    val longitudinalGrip: Double = 1.0,
    val rollingResistance: Double = 65.0,
    val speedLimitSoftness: Double = 0.18,
    val yawAssistMinSpeed: Double = 0.8,
    val yawAssistMaxSpeed: Double = 12.0,
    val driftMinSpeed: Double = 5.0,
    val driftStartSteer: Double = 0.2,
    val driftFrontGripScale: Double = 0.9,
    val driftRearGripScale: Double = 0.48,
    val driftYawAssist: Double = yawAssist * 1.35,
    val driftBrakeScale: Double = 0.16,
    val driftDriveScale: Double = 0.82,
    val driftExitSmoothingTime: Double = 0.18,
    val driftTopSpeedMultiplier: Double = 1.08,
    val driftUprightStrengthScale: Double = 1.45,
    val driftUprightDampingScale: Double = 1.35,
    val groundedGraceTime: Double = 0.1,
    val driftBoostEnabled: Boolean = true,
    val driftBoostMaxLevel: Int = 3,
    val driftBoostChargeTimes: List<Double> = listOf(0.8, 1.6, 2.6),
    val driftBoostForces: List<Double> = listOf(5200.0, 7600.0, 10400.0),
    val driftBoostDurations: List<Double> = listOf(0.35, 0.55, 0.8),
    val maxStepHeight: Double = 1.0,
    val stepAssistStrength: Double = 7200.0,
    val groundNormalSmoothingTime: Double = 0.12,
    val suspensionDroopGroundedFraction: Double = 0.45,
    val suspensionDroopPreloadFraction: Double = 0.16
) {
    companion object {
        val DEBUG_KART = KartPhysicsConfig(
            mass = 320.0,
            collisionBoxSize = Vector3d(1.25, 0.5, 1.55),
            collisionBoxOffset = Vector3d(0.0, 0.28, 0.0),
            wheelLocalPositions = listOf(
                Vector3d(-0.55, -0.12, 0.62),
                Vector3d(0.55, -0.12, 0.62),
                Vector3d(-0.55, -0.12, -0.62),
                Vector3d(0.55, -0.12, -0.62)
            ),
            wheelRadius = 0.28,
            wheelSampleWidth = 0.36,
            wheelSweepTime = 0.05,
            suspensionRestLength = 0.28,
            suspensionTravel = 0.34,
            suspensionStrength = 36000.0,
            suspensionDamping = 4200.0,
            driveForce = 8200.0,
            brakeForce = 5200.0,
            parkingBrakeStrength = 5.0,
            lateralGrip = 0.82,
            maxSteerRad = Math.toRadians(32.0),
            wheelTopSpeed = 19.0,
            yawAssist = 2600.0,
            uprightStrength = 6200.0,
            uprightDamping = 1050.0,
            maxSteerHighSpeedRad = Math.toRadians(18.0),
            steeringHighSpeedStart = 6.0,
            steeringFullSpeed = 18.0,
            steerSmoothingTime = 0.1,
            tireFrictionCoefficient = 1.32,
            frontLateralGrip = 1.08,
            rearLateralGrip = 0.74,
            lateralSlipShape = 0.44,
            longitudinalGrip = 1.24,
            rollingResistance = 24.0,
            speedLimitSoftness = 0.22,
            yawAssistMinSpeed = 1.2,
            yawAssistMaxSpeed = 18.0,
            driftMinSpeed = 5.0,
            driftStartSteer = 0.22,
            driftFrontGripScale = 0.9,
            driftRearGripScale = 0.3,
            driftYawAssist = 3800.0,
            driftBrakeScale = 0.0,
            driftDriveScale = 0.92,
            driftExitSmoothingTime = 0.2,
            driftTopSpeedMultiplier = 1.08,
            driftUprightStrengthScale = 1.45,
            driftUprightDampingScale = 1.35,
            groundedGraceTime = 0.1,
            driftBoostEnabled = true,
            driftBoostMaxLevel = 3,
            driftBoostChargeTimes = listOf(0.75, 1.5, 2.45),
            driftBoostForces = listOf(4600.0, 6800.0, 9200.0),
            driftBoostDurations = listOf(0.32, 0.5, 0.72),
            maxStepHeight = 1.0,
            stepAssistStrength = 7200.0,
            groundNormalSmoothingTime = 0.12
        )
    }
}

data class KartRuntimeState(
    var engineOn: Boolean = false,
    var debugSpeed: Double = 0.0,
    var debugGroundedWheels: Int = 0,
    var debugSteerRad: Double = 0.0,
    var debugThrottle: Double = 0.0,
    var smoothedSteerRad: Double = 0.0,
    var debugForwardSpeed: Double = 0.0,
    var debugLateralSlip: Double = 0.0,
    var drifting: Boolean = false,
    var driftDirection: Double = 0.0,
    var driftExitTimeRemaining: Double = 0.0,
    var driftBoostCharge: Double = 0.0,
    var driftBoostLevel: Int = 0,
    var driftBoostTimeRemaining: Double = 0.0,
    var driftBoostForce: Double = 0.0,
    var frontWheelSpin: Double = 0.0,
    var rearWheelSpin: Double = 0.0,
    var frontWheelAngularVelocity: Double = 0.0,
    var rearWheelAngularVelocity: Double = 0.0,
    var frontWheelSuspensionOffset: Double = 0.0,
    var rearWheelSuspensionOffset: Double = 0.0,
    var groundedGraceTimeRemaining: Double = 0.0,
    val smoothedGroundNormal: Vector3d = Vector3d(0.0, 1.0, 0.0),
    val partStates: MutableMap<String, VehiclePartState> = HashMap()
)
